spring:
  datasource:
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: HikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: matemaster
    url: jdbc:mysql://domain:3306/StandardWebServerConfigCenter

configurable: yaml