spring:
  # docker-mysql
  datasource:
    url: jdbc:mysql://localhost/StandardWebServerConfigCenter
    username: root
    password: wFj9LMRCbeE1gJKZ
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
      minimum-idle: 10
      pool-name: HikariCP
      driver-class-name: com.mysql.cj.jdbc.Driver
      connection-test-query: 'select 1'
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.elasticsearch.ElasticsearchDataAutoConfiguration


infrastructure:
  # docker-redis
  redis:
    enable: true
    host: localhost
    port: 6379
    password: D43bsV5sv0Fu5a62
    max-wait-mills: -1
    max-total: 8
    max-idle: 8
    min-idle: 0
    test-while-idle: true
    block-when-exhausted: true
    info: true
    fairness: false
    jmx-enabled: true
