spring:
  profiles:
    active: prd
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: 8081

mybatis:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  packages-to-scan: cs.matemaster.standardwebserver.controller
  swagger-ui:
    supported-submit-methods: get,post

activity-prepare:
  activity-prepare-principal-map:
    PrizeAward:
      dev: 11
      operation: 22
      well-known-people: 33
    LiveStreaming:
      dev: 11
      operation: 22
      well-known-people: 33