springdoc:
  packages-to-scan: cs.matemaster.tech.qiniuyun
  swagger-ui:
    supported-submit-methods: get,post

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-request-size: 10MB
      max-file-size: 10MB